// Generated by scripts/generate-l10n-catalog.py — do not edit by hand.
import Foundation

enum L10nCatalog {
    private static let table: [String: [String: String]] = loadTable()

    private static func loadTable() -> [String: [String: String]] {
        guard let url = Bundle.module.url(forResource: "L10nCatalog", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([String: [String: String]].self, from: data)
        else {
            assertionFailure("Missing L10nCatalog.json in CommonGroundCore bundle")
            return [:]
        }
        return decoded
    }

    static func translation(for key: String, language: AppLanguage) -> String? {
        guard language != .system, let row = table[key] else { return nil }
        return row[language.rawValue] ?? row["en"]
    }
}
